apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    name: catalog
spec:
  ports:
    - port: 80
  selector:
    name: catalog
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: catalog
  labels:
    name: catalog
spec:
  replicas: 4
  selector:
    name: catalog
  template:
    metadata:
      labels:
        name: catalog
    spec:
      containers:
      - name: catalog
        image: moredip/pretend_catalog_service:latest
        ports:
        - containerPort: 80
