apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
spec:
  ports:
    - port: 5432
  selector:
    name: db
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: db
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
