apiVersion: v1
kind: Service
metadata:
  name: deals
  labels:
    name: deals
spec:
  ports:
    - port: 80
  selector:
    name: deals
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: deals
  labels:
    name: deals
spec:
  replicas: 4
  selector:
    name: deals
  template:
    metadata:
      labels:
        name: deals
    spec:
      containers:
      - name: deals
        image: moredip/pretend_deals_service:latest
        ports:
        - containerPort: 80
