apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    name: web-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: web-app
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: web-app
  labels:
    name: web-app
spec:
  replicas: 2
  selector:
    name: web-app
  template:
    metadata:
      labels:
        name: web-app
    spec:
      containers:
      - name: web-app
        image: moredip/pretend_web_app:latest
        ports:
        - containerPort: 80
